### ISSUE TITLE
Looks like the app doesn't know how to handle numbers starting with 0

### ISSUE THREAD

**Issue by andremarcondesteixeira** [GhitaB/guess-my-number#10]
From times to times, I stumble across some unsolvable numbers. The last example was 0395, but the app only will identify the last 3 digits. You can test the issue by typing 0 to 9, sequentially and isolated. (type 0, enter, type 1, enter, and so on, so you can test all the 10 numbers)

**Comment by andremarcondesteixeira** [comment]
I just got another example:

![image](https://user-images.githubusercontent.com/4294962/33134498-05f3d0f0-cf87-11e7-8a3e-0d611fb0997c.png)

**Comment by andremarcondesteixeira** [comment]
Well, actually, the zero is not the problem, but the app is generating repeated numbers:

![image](https://user-images.githubusercontent.com/4294962/33135128-aef1a136-cf88-11e7-9cf0-1bb607d1b5d9.png)

**Comment by GhitaB** [comment]
Oh, something is broken. Thanks!
Also there must be a validation: "Your number" must have 4 digits. I can't believe it's not already implemented. :))

Please feel free to contribute (fork + pull request).

**Comment by GhitaB** [comment]
@andremarcondesteixeira Solved. :)
