### ISSUE TITLE
So easy

### ISSUE THREAD

**Issue by lrusnac** [GhitaB/guess-my-number#3]
So easy to win :D just put a debug and watch the stack ![schermata 2015-05-17 alle 13 32 04](https://cloud.githubusercontent.com/assets/1005173/7670141/2dcd04ca-fc99-11e4-9882-5c4b54b304cc.png)

**Comment by jamesliu96** [comment]
LOL, awesome!

**Comment by GhitaB** [comment]
Yes. You discovered a cheat for this game. :smiley_cat: 
Do you have any solution to fix this?

**Comment by jamesliu96** [comment]
@GhitaB the only solution that can fix this thoroughly is to create a remote server that generates and processes the random number.

**Comment by GhitaB** [comment]
Thank you, @jamesliu96!
But this is hosted on GitHub Pages that is client side only...

**Comment by jamesliu96** [comment]
@GhitaB Yeah, well then, this problem therefore cannot be solved. But this project is nice, especially for the designing!

**Comment by GhitaB** [comment]
Thank you. I use http://coolors.co/ for nice color schemes.

**Comment by lrusnac** [comment]
Nice project but I don't really understand the difference with [Mastermind](http://en.wikipedia.org/wiki/Mastermind_%28board_game%29). And yes the better way is to have a server side for hiding the computer number :) :+1:

**Comment by GhitaB** [comment]
I used to play this game on paper with my brother some years ago. I don't know the real name of this game. Maybe it is the same with Mastermind.

**Comment by h0dgep0dge** [comment]
I imagine this bug could be partially solved with some kind of cryptographic black magic without the need for a smart back end server. This is not exactly my forte, but I may do some research on it

**Comment by GhitaB** [comment]
Maybe yes. Try it.
